## Homework Week 4

Տնայինի այս մասում փորձելու եք իրականացնել backpropagation (BP) ալգորիթմը:

BP ալգորիթմի նպատակն է այնպես փոփոխել մեր ցանցի պարամետրերը՝ W-երը և b-երը, որ loss-ը մաքսիմալ փոքր լինի: Այսինքն՝ եթե ծաղիկը A տեսակի է, ապա մենք ուզում ենք, որ ցանցին այդ ծաղիկի ցողունի բարձրությունը և պսակի տրամագիծը տալով, այն ինչքան հնարավոր է (1,0)-ին մոտ output տա, օրինակ՝ (0.98, 0.15)-ը շատ լավ արդյունք է, քանի որ թվերին նայելով կարող ենք ասել, որ ցանցը վստահ է, որ ծաղիկը A տեսակի է:

<font color='green'>Նշում:</font> Ինչպե՞ս ենք որոշում ցանցը ինչ է գուշակում՝ A, թե B: Դրա համար մոտեցումը շատ պարզ է. համեմատում ենք output-ի երկու թվերը և կախված, թե որն է մեծ, ասում ենք ցանցը գուշակում է A, եթե առաջին թիվը մեծ է երկրորդից և B` հակառակ դեպքում:

Գիտենք, որ loss կամ cost ֆունկցիան ֆունկցիա է ցանցի պարամետրերից կախված: Իրականում այն ֆունկցիա է ոչ միայն պարամետրերից, այլև input(X)-ից և target(Y)-ից, բայց քանի որ սրանք տրված են, ապա այն կոնկրետ training example-ի համար ֆունկցիա է միայն պարամետրերից: Քանի որ պարամետրերի քանակը շատ մեծ է և կախվածությունն էլ բավականին բարդ տեսքի է, ապա մենք անալիտիկ տեսքով չենք կարող ստանալ W-երի և b-երի այն արժեքները, որոնց դեպքում loss-ը մինիմում է:
<br> Այդ նատակով մենք օգտագործում ենք իտերատիվ ալգորիթմ՝ Gradient descent (GD), որի իմաստը հետևյալն է՝
-  նախ հաշվում ենք Cost function (CF)-ի մասնակի ածանցյալները ըստ բոլոր պարամետրերի, այլ կերպ ասած՝ գրադիենտները,
-  ապա բոլոր պարամետրերի արժեքները update ենք անում հետևյալ բանաձևի միջոցով՝ W_new = W_old - alpha * grad_W, նմանապես բոլոր b-երի համար (alpha-ն learning rate(lr)-ն է, որի միջոցով կառավարում ենք ցանցի սովորելու արագությունը, սովորաբար դրվում է փոքր թիվ, օրինակ՝ 0.01)

__Սկզբի համար W-ների և b-երի գրադիենտները կհաշվենք միայն առաջին ծաղիկի համար:__
<br><font color='red'> Քանի որ մեր օրինակը շատ նման է հոդվածի թվային օրինակին, հետևաբար հիմնական բանաձևերը և դրանց դուրսբերումը պետք է նայել հոդվածում:</font>
<br>    https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/


<font color='magenta'> ՀԱՏԿԱՊԵՍ ԱՅՍՏԵՂ Է ՊԵՏՔ ԳԱԼՈԻ ՁԵՐ ՆԿԱՐԱԾ ՑԱՆՑԸ:</font>

<br><font color='Blue'> Նշում: Այսուհետ Cost function-ի մասնակի ածանցյալը ըստ որևէ W-ի, b-ի կամ output-ի ուղղակի կանվանենք տվյալ __W-ի, b-ի կամ output-ի գրադիենտ__, համապատասխանաբար Cost function-ի մասնակի ածանցյալը ըստ որևէ շերտի նեյրոնների կանվանենք __տվյալ շերտի նեյրոնների գրադիենտ__:</font>

In [1]:
import numpy as np

In [2]:
W1 = np.array([[ 0.51,  0.41],
               [ 0.34,  0.24],
               [ 0.25, -0.14],
               [-0.62, -0.42]])

b1 = np.array([-0.65,  0.27,  0.58,  0.16])

In [3]:
W2 = np.array([[-0.41, -0.38,  0.22,  0.1 ],
            [-0.16,  0.3 ,  0.02,  0.03]])

b2 = np.array([0.49, 0.41])

In [4]:
X = np.array([[26.86,  6.86],
               [29.48,  8.57],
               [29.63,  8.01],
               [33.74,  7.  ],
               [18.54,  6.97],
               [15.98,  5.69],
               [19.01,  4.5 ]])


Y = np.array([["A"],
              ["A"],
              ["A"],
              ["A"],
              ["B"],
              ["B"],
              ["B"],])

In [5]:
X[:,0] -= np.mean(X[:,0])
X[:,1] -= np.mean(X[:,1])

X[:,0] /= np.var(X[:,0])
X[:,1] /= np.var(X[:,1])

In [6]:
Y = np.array ([[1,0] if i[0]=="A" else [0,1] for i in Y])

In [7]:
class Linear():
    def __init__ (self, W, b):
        self.W = W
        self.b = b
        self.output = None
        
    def forward(self, inpt):
        self.output = np.dot(inpt, self.W.T) + self.b
        return self.output
        pass

In [8]:
class Sigmoid():
    def __init__ (self):
        self.output = None
        
    def forward(self, inpt):
        self.output = 1/(1 + np.exp(-inpt))
        return self.output
        pass

In [9]:
class MSECriterion():
    def __init__ (self):
        self.output = None
        
    def forward(self, inpt, target):
        self.output = np.mean((inpt - target)**2)
        return self.output
        pass

In [10]:
Layer1_linear = Linear(W1, b1)
Layer1_sigmoid = Sigmoid()
Layer2_linear = Linear(W2, b2)
Layer2_sigmoid = Sigmoid()
Layer_Loss = MSECriterion()

In [11]:
Z1 = Layer1_linear.forward(X)
A1 = Layer1_sigmoid.forward(Z1)
Z2 = Layer2_linear.forward(A1)
A2 = Layer2_sigmoid.forward(Z2)
Loss = Layer_Loss.forward(A2, Y)

# Քայլ 1

## Առաջադրանք N10

__Հաշվել առաջին ծաղիկի համար OUTPUT շերտի նեյրոնների, այսինքն՝ ցանցի output-ների գրադիենտները:__ 

<font color='Green'> Հուշում: Գրեք Cost function-ի բանաձևը՝ կախված ցանցի output-ներից ու Y-ներից ու ածանցեք՝ հաշվի առնելով, որ Y-ները տրված են ու փոփոխականը միայն output-ներն են:</font>

In [13]:
def grad_loss(layer2_sig, y):
    return (layer2_sig - y)/layer2_sig.shape[0]

In [14]:
grad_loss(A2, Y)

array([[-0.06003895,  0.09073618],
       [-0.06321942,  0.09065347],
       [-0.0622405 ,  0.09069046],
       [-0.06077643,  0.09074507],
       [ 0.08322194, -0.05214487],
       [ 0.08546337, -0.05217105],
       [ 0.08703655, -0.05222023]])

## Առաջադրանք N11

__Հաշվել output շերտի գծային շերտի նեյրոնների output-ների գրադիենտները:__ 

<font color='Green'> Հուշում: Հաշվի առեք, որ Cost function-ի կախվածությունը OUTPUT շերտի գծային շերտի նեյրոնների output-ներից բարդ ֆունկցիա է, հետևաբար Cost function-ի մասնակի ածանցյալը ըստ դրանց ստացվում է երկու ածանցյալների արտադրյալ՝ նախորդ քայլում հաշված output-ների գրադիենտների և երկրորդ արտադրիչը OUTPUT շերտի ոչ գծային շերտի output-ների ածանցյալն է դրա գծային շերտի output-ներից, այսինքն՝ փաստացի երկրորդ արտադրիչը սիգմոիդի ածանցյալն է ստացվում:</font>

In [15]:
def grad_output_lin(layer2_sig):
    return (layer2_sig * (1 - layer2_sig)) * grad_loss(A2, Y)

In [16]:
grad_output_lin(A2)

array([[-0.0146281 ,  0.02102662],
       [-0.0155961 ,  0.02102161],
       [-0.01530266,  0.02102386],
       [-0.01485619,  0.02102715],
       [ 0.02023832, -0.01208607],
       [ 0.02054097, -0.01209472],
       [ 0.0207202 , -0.01211097]])

## Առաջադրանք N12

__Հաշվել W2-ի և b2-ի գրադիենտները:__ 

<font color='Green'> Հուշում: Այս դեպքում արդեն Cost function-ի կախվածությունը W2-ից և b2-ից "ավելի" բարդ ֆունկցիա է ու ածանցյալը 3 բաղադրիչների արտադրյալ է: Այդ 3 բաղադրիչներից 2-ը նախորդ առաջադրանքի արտադրիչներն են, որոնց արտադրյալը հաշվել ենք՝ 
output շերտի գծային շերտի նեյրոնների output-ների գրադիենտներն են:
<br> Այսինքն` նորից երկու արտադրիչ ենք բազմապատկում, որոնցից մեկը արդեն հաշվել էինք, իսկ մյուսը ստանում ենք՝ OUTPUT շերտի գծային շերտի նեյրոնների output-ների բանաձևը գրելով և համապատասխանաբար ըստ W2-ի և b2-ի տարրերի ածանցելով: Կախվածությունը գծային է, հետևաբար շատ պարզ բանաձև է ստացվում:</font>

In [68]:
def grad_W2(layer1_sig):
    return np.dot(grad_output_lin(A2).T, layer1_sig)

In [69]:
grad_W2(A1)

array([[-0.00817768, -0.0052084 ,  0.00199982,  0.01078659],
       [ 0.02453323,  0.03245409,  0.02947062,  0.01633288]])

In [19]:
def grad_b2():
    return np.sum(grad_output_lin(A2), axis = 0)

In [20]:
grad_b2()

array([0.00111643, 0.04780749])

# Քայլ 2

## Առաջադրանք N13

__Հաշվել HIDDEN շերտի output-ների գրադիենտները:__ 

__Մաս 1__ 

<font color='Green'> Հուշում: Այս դեպքում նույն սկզբունքն ենք կիրառում, ինչ-որ նախորդ առաջադրանքներում, այսինքն՝ օգտագործում ենք ածանցյալի շղթայական կանոնը: Մեզ պետք են գալու OUTPUT շերտի գծային շերտի output-ները: Սակայն մեկ բան պետք է հաշվի առնել՝ HIDDEN շերտի output-ները մի քանի ճանապարհով են ազդում Cost function-ի վրա:</font>

_Հարց. մեր դեպքում քանի՞ ճանապարհով են ազդում:_

 ազդում են 2 ճանապարհով


__Մաս 2__ 

<font color='Green'> Հուշում: Քանի որ մեկից ավել ճանապարհով են ազդում, հետևաբար HIDDEN շերտի output-ների գրադիենտները ստացվում են ճանապարհների քանակով գումարելիների գումար:</font>

In [42]:
def grad_hidden():
    return np.dot(grad_output_lin(A2), W2)

In [45]:
grad_hidden()

array([[ 0.00263326,  0.01186667, -0.00279765, -0.00083201],
       [ 0.00303094,  0.012233  , -0.00301071, -0.00092896],
       [ 0.00291027,  0.01212217, -0.00294611, -0.00089955],
       [ 0.00272669,  0.0119535 , -0.00284782, -0.0008548 ],
       [-0.00636394, -0.01131638,  0.00421071,  0.00166125],
       [-0.00648664, -0.01143398,  0.00427712,  0.00169125],
       [-0.00655753, -0.01150696,  0.00431622,  0.00170869]])

## Առաջադրանք N14

__Հաշվել HIDDEN շերտի գծային շերտի նեյրոնների output-ների գրադիենտները:__

In [47]:
def grad_hidden_lin(layer1_sig):
    return layer1_sig * (1 - layer1_sig) * grad_hidden()

In [52]:
grad_hidden_lin(A1)

array([[ 0.00060109,  0.00290221, -0.00064229, -0.00020736],
       [ 0.00075426,  0.00281803, -0.00071509, -0.00022412],
       [ 0.00071374,  0.00285351, -0.00069157, -0.00022185],
       [ 0.00064326,  0.00288494, -0.00064794, -0.00021365],
       [-0.00141775, -0.00278783,  0.00098302,  0.0004107 ],
       [-0.00124771, -0.0028579 ,  0.00097207,  0.00038832],
       [-0.00109541, -0.0028657 ,  0.00094199,  0.00035798]])

## Առաջադրանք N15

__Հաշվել W1-ի և b1-ի գրադիենտները:__ 

In [61]:
def grad_W1(input_x):
    return np.dot(grad_hidden_lin(A1).T, input_x)

In [64]:
grad_W1(X)

array([[ 0.00100378,  0.00376956],
       [ 0.0029548 ,  0.01155944],
       [-0.0008497 , -0.0033457 ],
       [-0.00031291, -0.00119144]])

In [71]:
def grad_b1():
    return np.sum(grad_hidden_lin(A1), axis = 0)

In [73]:
grad_b1()

array([-0.00104853,  0.00294725,  0.00020019,  0.00029002])

# Քայլ 3

## Առաջադրանք N16

__Կատարել պարամետրերի update. alpha = 0.5:__ 

In [89]:
def update_grad(W2 = W2, b2 = b2, W1 = W1, b1 = b1, alpha = 0.5):
    delta_W2 = grad_W2(A1)
    delta_b2 = grad_b2()
    delta_W1 = grad_W1(X)
    delta_b1 = grad_b1()
    
    W2 = W2 - alpha * delta_W2
    b2 -= alpha * delta_b2
    W1 -= alpha * delta_W1
    b1 -= alpha * delta_b1

In [90]:
print(W1)

update_grad()

print(W1)

[[ 0.51  0.41]
 [ 0.34  0.24]
 [ 0.25 -0.14]
 [-0.62 -0.42]]
[[ 0.50949811  0.40811522]
 [ 0.3385226   0.23422028]
 [ 0.25042485 -0.13832715]
 [-0.61984354 -0.41940428]]


## Առաջադրանք N17

__Հաշվել բոլոր պարամետրերի գրադիենտները բոլոր ծաղիկների համար և կատարել update (alpha = 0.1):__

__Բոլոր պարամետրերի գրադիենտները բոլոր ծաղիկների համար__ իրականում նշանակում է առանձին-առանձին բոլոր յոթ ծաղիկների համար հաշվարկված պարամետրերի գրադիենտների գումար:
<br>Իմաստը այն է, որ հերթով բոլոր ծաղիկների համար առանձին գրադիենտները հաշվելու ու պարամետրերը update անելու փոխարեն, մենք բոլորինը միանգամից ենք update անում, այսինքն՝ յոթ անգամ _մանր_ update անելու փոխարեն, մեկ անգամ _խոշոր_ update ենք անում, որը պարունակում է բոլոր 7 update-ների ինֆորմացիան:
<br> Խոսքը վերաբերում է միայն պարամետրերին, իսկ նեյրոնների գրադիենտները ստացվում են նեյրոնների մատրիցների չափով, այսինքն՝ HIDDEN շերտում` 7x4,  OUTPUT շերտում՝ 7x2:

<font color='Green'> Հուշում:
Դա կարելի է անել 2 տարբերակով՝
-  __Տարբերակ 1__
<br> հաշվում եք յոթ ծաղիկների համար պարամետրերի գրադիենտները առանձին-առանձին և դրանք գումարում եք իրար
-  __Տարբերակ 2__
<br> այդ ամենը անում եք մատրիցային տեսքով<font>

<font color='magenta'> ՁԵԶԱՆԻՑ ՊԱՀԱՆՋՎՈՒՄ Է ԻՐԱԿԱՆԱՑՆԵԼ ՏԱՐԲԵՐԱԿ 2-Ը:</font>

<br><font color='Blue'> Ուշադրություն: OUTPUT շերտի գրադիենտները տարբեր են ստացվում առանձին ծաղիկների համար հաշվարկված գրադիենտներից, քանի որ Cost function-ի բանաձևը տարբեր է, մասնավորապես, այն բազմապատկված է 1/7-ով:</font>

In [91]:
print(W1)

update_grad(alpha = 0.1)

print(W1)

[[ 0.50949811  0.40811522]
 [ 0.3385226   0.23422028]
 [ 0.25042485 -0.13832715]
 [-0.61984354 -0.41940428]]
[[ 0.50939773  0.40773827]
 [ 0.33822712  0.23306433]
 [ 0.25050982 -0.13799258]
 [-0.61981225 -0.41928514]]
